### ISSUE TITLE
Clarification on case-sensitivity of platform properties

### ISSUE THREAD

**Issue by roitk** [bazelbuild/remote-apis#109]
Are the platform properties (names and values) case-sensitive? As far as I can tell, there's no explicit specification in the proto file.

My assumption is that they are, given the rendering of "OSFamily" as well as the following statement in [platform.md](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/platform.md):

> Multiple values are not allowed and **an exact match is required**.

**Comment by bergsieker** [comment]
The properties *should* be case-insensitive. However, I know that RBE doesn't respect this, and I suspect that other implementations may not either.

**Comment by edbaunton** [comment]
As I recall, buildbox and BuildGrid is case sensitive, worth a clarification in the spec?

**Comment by EricBurnett** [comment]
If BuildBox, BuildGrid, and RBE are all case-sensitive (others unknown), and the current text implicitly reads as case-sensitive, then I guess we should clarify the text to be _explicit_ that it's case sensitive? If anyone cares strongly we can consider relaxing that in V3. (@bergsieker : I agree this may not be the ideal answer, but seems this ship has sailed).

Of course, servers are free to accept nonstandard casing anyways since they can accept any keys they want, so I don't think it harms them at all to define it this way. Might put clients currently sending incorrect casing out of spec though - if anyone has such a client, please say so!
