### ISSUE TITLE
Provide recommendations for platform properties labelling

### ISSUE THREAD

**Issue by werkt** [bazelbuild/remote-apis#117]
Implementors of remote apis should have some guidance for useful identification of action runtime specifications like cores, memory, disk, bandwidth, and boundings (min/max) for all of those.

This issue is a discussion point for these recommended field names, values, and the ability to encapsulate and translate them throughout an operation's lifecycle in any given implementation.

**Comment by bergsieker** [comment]
I'm not sure that it's possible to do this usefully, because the scheduling/matching semantics will always be specific to the server. For instance, if the client requests 2 cores, should the server interpret that as exactly 2 cores, or at least 2 cores? Unless we specify *both* the keys and their interpretation, which I feel is far too prescriptive, then there will still be ambiguity and skew between implementations (arguably it's actually *worse* if you have standard keys and non-standard interpretations because moving to a new backend might change behavior in subtle ways rather than obvious ones).

**Comment by werkt** [comment]
> For instance, if the client requests 2 cores, should the server interpret that as exactly 2 cores, or at least 2 cores?
Hence the bounding notation in description. Either forced bounding, or no more, or no less, possibly both, where it makes sense.

> Unless we specify _both_ the keys and their interpretation, which I feel is far too prescriptive
That's exactly what I'm proposing for these broad concepts, to a point where the remote system should enforce limits as requested. i.e. min-memory 1G means that steps should be taken to provide access to an uncontested 1G of memory. Specifically that 'supporting' one of these properties 'means' that you can do X.

**Comment by sstriker** [comment]
+1.

I'm personally not that opposed to being more prescriptive for sake of
consistency across implementations and there for better compatibility
between services, ideally without having to reconfigure clients other than
the endpoint to use.  However... consensus on that is hard.

Maybe we can agree though that labels exist to designate some sense of
sizing without dictating what the actual size is in terms of cpu/mem eg.
nano, micro, small, medium, large, xlarge, 2xlarge, 4xlarge.

For situations where there are more specific requirements eg. 2 cores, no
less no more, at least 2G of memory, a set of standardized properties is
useful, where we can be descriptive on what they mean.  It's up to services
to decide whether to respect these constraints or to error.

**Comment by bergsieker** [comment]
Per discussion in monthly sync: so far there's only one party interested in this, and at least one party actively imposed (because they believe that giving clients too much control over resource allocation will converge into all clients specifying max resources). Implementing and maintaining a standard like this would be significant work, so we'd want to have a stronger signal of interest. We could make it an optional extension to the API, but once it's optional it's no longer a standard, so there's not much value in doing so.

This may be revived in the future as standardization becomes more important.
