### ISSUE TITLE
Two-phase caching and dynamic remote execution proposal

### ISSUE THREAD

**Issue by erikma** [bazelbuild/remote-apis#156]
Issue for PR #155 discussion. That PR proposes the following high-level changes to the protocol:

* Optional additions to the ActionCache API that allow two-phase action cache lookups. Two-phase caching deals with underspecified inputs, e.g. when predicting inputs for a C++ compiler where the `#include`d headers in .cpp files outside of system header directories are not known ahead of time, by allowing an `Action` to contain an incompletely specified filesystem. That possibly-incomplete Action hash leads to a list of zero or more possible matches, where a new data structure `ObservedPathSet` is used to perform an ordered comparison to the client's current filesystem to build up an observed-input digest. On a match to the observed-input digest seen on the worker, the resulting `ActionResult` can be retrieved to produce a cache hit.

* Optional additions to the Execution API that work with two-phase caching to provide a two-way execution contract where files and directories that were not predicted to be used by the action can be retrieved dynamically, with path probes sent back to the client and resulting Directory metadata, file hashes, and file contents pushed to the worker in real time to resolve pending filesystem requests. The typical worker implementation in this case utilizes a virtual filesystem to allow pausing filesystem I/O requests in the OS kernel until dynamic file and directory requests can be resolved. The net effect is to allow remote execution when the action's inputs are incompletely specified.

* Optional ActionResult extension to provide higher fidelity console outputs, where stdout and stderr lines or multi-line blocks are interleaved. This provides higher fidelity from cache results and allows incremental real-time console streaming from the bidirectional dynamic execution API.

This protocol is derived from an internal gRPC protocol utilized in https://github.com/AnyBuild/AnyBuild currently in use internally at Microsoft. This issue and related PR are intended to remain open as draft until AnyBuild is refactored to implement the proposal to ensure it is complete.

**Comment by EricBurnett** [comment]
Hi Erik,

Thanks for the PR, and for sharing all your work here! It's very interesting to see concretely what you've been working on and been talking about.

I'll preface this by saying I'm somewhat conflicted about this proposal itself -
 - On one hand, it's a very neat way to achieve your goals of remote execution for under-specified actions, and certainly better than not remoting or caching them at scale. Nice work, Erik and co!
 - On the other hand, to the extent we have any influence over the tooling ecosystem I'd like to push tools _away_ from under-specified actions and conversational patterns as much as possible, and suggest implementation of this API only as a last resort. And even there, it doesn't look like it'd be an easy transition from 2-phase RE to 1-phase RE once adopted, so it represents a local maxima that anyone who starts using will probably have a lot of trouble getting out of (yourselves included :( ).

I'm not sure how to reconcile this. My first thought is something along the lines of _"we should accept this API if there are other existing collaborators who want to implement it, but put it off to the side somewhere (minimally, a different file) with strong warnings around it"_. And in particular, I'd suggest that folk only implement this API if they have an immoveable codebase (can't get to modern build tools even with years of lead time) and a decently sized team to implement and then debug/optimize over time (e.g. input prediction must be kept effective as things change). Are those fair warnings, from your perspective?

In concrete terms, I have issues with this sort of API that make me not want to see it broadly used (most being general to _any_ API of this form, not specific to your implementation). You're probably well aware of these, but I'll call them out explicitly for other reviewers to consider. In no particular order:
 - **Performance**
    - **Cache hits are more expensive** - they go from being a simple lookup to being a (potentially) large response + decision tree application, or O(potential_hits * unspecified_files) matching scheme.
       - Note that cost of cache hits is already a concern with the existing API, and there are proposals to e.g. relax the merkle tree scheme to make them cheaper yet, because right now just enumerating and building a tree of concrete inputs is expensive. Having to do that, and _then_ some large sequences of file operations (even virtualized) and additional hashes would be more expensive yet.
    - **Cache hits are less frequent** - e.g. presence/absence of unrelated files will interfere with caching, and scaling limits on actions with many candidates (due to under-guessed inputs) will degrade further.
    - **In-flight deduping is lost** - in the normal case, this "only" reduces performance by XX% (low tens, on workloads we run), but under times of contention when e.g. something fundamental changes and a whole bunch of cache-miss builds trigger at once, you can get a bunch of builds asking for the same things at once, and even moreso with queueing (since clients would check the cache *before* the action spends time in a queue waiting for a worker). Generally means a lot more effort must go into keeping the stack un-saturated, or cache-invalidating events become much more expensive and take much longer to recover from.
 - **Security**
    - **Introduces new information-stealing scenarios** to defend against.
 - **Flexibility**
    - At least as written, this appears fairly inflexible - requires a strong coupling to how the client and server operate (e.g. VFS remotely, sequence of stat calls required by client), which looks like it'd make it hard to optimize or use in new and novel ways. That's somewhat counter to the goals of this family of APIs, which are for simple and powerful constructs (as much as we can manage, anyways) that can be combined into various forms for various purposes. Though this one may not be fundamental - we'll see how discussions on the PR go and if some of the generality/flexibility can be added.
 - **Complexity**
    - **For implementers**, pulls in all the complexity of the existing REAPI _and_ a whole lot more. Looks pretty daunting at first blush.
    - **For users**, there are now a lot of new performance scenarios to be concerned about, which is a challenge area for users already. Poor input prediction can waste time on checking for more potential cache hits, require a lot of additional round-trips, reduce cache hit rates by over-predicting, and possibly more.
    - **Debugging** is similarly harder - e.g. adds to existing debuggability issues actions that hit some timeout or behave differently when the VFS fault-in takes too long, and unpredictable performance in general; flakiness on long-running actions due to lack of resumption.

Predicting how this combines together is a terrible idea, but I'll still say that my gut feel is builds using the dynamic API will net out 2-4x as expensive per-build than the equivalent workloads running through the existing REAPI, due to reduced cache hits and increased worker costs and fullness costs. Sound plausible?

None of this is a hard deal-breaker for folk implementing it, to be clear - we can make the API as clean and easy as possible, and if they're stuck between simply re-executing everything all the time and implementing this API, hopefully they'll be better off implementing it. I just want to be very aware that the third option of _"pay down the debt to move to a build tool where inputs are known"_  is likely a better choice for all but the oldest and most ossified codebases, and very much remains my personal preference to focus on and push folk towards, with this API necessarily somewhat sidelined as a result of that.

(Whew. Apologies for the wall of text!)

**Comment by ulfjack** [comment]
We are very interested in implementing this. Unfortunately, we have been in a bit of a crunch in the last two weeks and I haven't even been able to go through my non-work email, let alone writing a prototype for two-phase caching.

We also discussed this in the REAPI meeting yesterday, where someone (@EdSchouten maybe?) proposed to start with smaller bits and pieces that are more generally useful, which sounds good to me.

**Comment by erikma** [comment]
Per PR comment, ConsoleOut changes were separated into #173.

**Comment by erikma** [comment]
Closing this issue and related PR: Though interesting for some community members, this proposal is unlikely to be accepted into the PE protocol (even for v3) as it needs a second implementation.
