### ISSUE TITLE
Clarification: GetTree() pages and relation with gRPC max. message size

### ISSUE THREAD

**Issue by santigl** [bazelbuild/remote-apis#89]
The `GetTreeRequest` parameter of the `GetTree()` call allows the client to set a `page_size` limit. According to the spec, "*the server may place its own limit [...] and require the client to retrieve more items using a subsequent request*".

Servers read the `page_token` field in requests and include a `next_page_token` in responses. That last token "*[i]f present, signifies that there are more results*" and "*[i]f empty, [...] the last page of results*".

My specific questions related to this are what would happen in the case where a `GetTreeResponse` message exceeds the maximum gRPC message size, and whether it would be correct to make a distinction between logical pages (defined by a token value) and physical pages (gRPC messages in the stream).

So, for example, if a client makes a `GetTree()` call without setting a limit, and the server is happy to return the whole tree, could the server split it into multiple `GetTreeResponses` without setting a `next_page_token` and expect the client's implementation to keep reading the stream?

That same scenario might also happen if the `page_size` given by the client produces a `GetTreeResponse` larger than the gRPC maximum message size. Could then a page span multiple `GetTreeResponse`s? Or should the server keep a 1:1 relationship between pages and messages?

Thank you, and sorry if this is something that is totally clear from reading the specification.

**Comment by EricBurnett** [comment]
Hi Santiago,

If the response is going to exceed the gRPC message size, the server should
break it up into multiple pages. The API doesn't draw a distinction between
'logical' and 'physical' pages - if the stream is paginated into multiple
messages for any reason (due to request page_size, server max page_size,
server calculated message size, etc) , it's handled the same - via each
message containing a next_page_token.

So for your example, if the client makes a GetTree() call with no limit,
the server should send a stream of GetTreeResponse messages back, with all
but the last embedding a next_page_token. That way if the stream is broken
for any reason, the client both knows (a) that it received an incomplete
response, and (b) has a way to resume where it left off.

Does that answer your question?
--E

**Comment by santigl** [comment]
Got it. Thank you very much for your reply, Eric.

**Comment by santigl** [comment]
Sorry for reviving this. Since my question is related, I figured it made sense to add a follow up here.

In the case where a `GetTreeRequest` specifies a `page_token`, should the server return only that page?

[This line in the spec](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L1309) says about `page token`: *"If present, the server will use it to return the following page of results."* Would it be correct to deduce, since "the following page" is singular, that the client only should receive that particular page?

Or rather is `page_token` meant to be interpreted as an offset from which the server must start streaming pages until reaching the end of the tree?

**Comment by EricBurnett** [comment]
It should be interpreted as an offset to start the stream at. This is
slightly clearer at
https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L314-L317
,
but I agree with you that the use of singular here is a bit misleading,
since the GetTreeRequest is requesting that page and all following.

Want to send a PR to correct?

**Comment by santigl** [comment]
Thanks again, Eric. 

I'd be glad to submit a PR to make it a bit more explicit.
